import './header.js';
import './filter-component.js';
import './tab-component.js';
import './form-component.js';
import './ficha-component.js'
import './lateral-menu-component.js';
import "./modal.js";
import "./erase-alert-component.js";
import  "./login-component.js"